## Description
The purpoes of this jupyter notebook is to investigate, train and predict boston housing price using Random Forest. 

* Model performance is evaluated using Mean Square Error (MSE) on validation set
* Use hyperparameter tuning to optimize the model's performance.

### Note: 
The Boston housing dataset is extracted from the URL: http://lib.stat.cmu.edu/datasets/boston

Since scikit-learn load_boston dataset is removed from version 1.2

### Outline Model Training Process:
1. Load Boston Housing Dataset
2. Preprocessing (if neccessary)
3. Feature selection (optional)
4. Model Training
5. Hyperparameter Tuning

# 1. Loading Boston Housing Dataset

In [2]:
import os
import pickle
import json
import pandas as pd
import numpy as np
import ssl
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [4]:
# Disable SSL verification
ssl._create_default_https_context = ssl._create_unverified_context

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]]) # 13 FEATURES
target = raw_df.values[1::2, 2] # MEDV

print(f"Boston dataset (features) shape: {data.shape}")
print(f"Boston dataset (target) shape: {target.shape}")

Boston dataset (features) shape: (506, 13)
Boston dataset (target) shape: (506,)

In [5]:
# Convert dataset to dataframe
columns = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", 
    "PTRATIO", "B", "LSTAT"
]

boston_df = pd.DataFrame(data, columns=columns)
boston_df['MEDV'] = target

boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2